language: java
jdk:
- oraclejdk8
dist: trusty

before_install:
- pyenv install 3.6.3 --skip-existing
- pyenv global system 3.6.3
- pip3 install --user codecov

script:
- mvn test
after_success:
- codecov
