logging:
  level:
    root: INFO
    generic: DEBUG

server:
  port: 8092
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        secure: true

# URL of the broker-gui to redirect back after authentication and the credentials of the broker-server to check against
broker:
  url: "http://localhost:8091"
  user: user
  password: secret


# Details on which inteken implementation to call including credentials
backend:
  url: "http://localhost:8093/intake"
  api_user: user
  api_password: secret

# Clean up enrollmentRequests every 15 minutes
cron:
  initialDelayMilliseconds: 900000
  fixedDelayMilliseconds: 900000

oidc:
  acr-context-class-ref: https://eduid.nl/trust/linked-institution
  client-id: student.mobility.rp.localhost
  client-secret: secret
  redirect-uri: http://localhost:8092/redirect_uri
  authorization-uri: https://connect.test2.surfconext.nl/oidc/authorize
  token-uri: https://connect.test2.surfconext.nl/oidc/token
  jwk-set-uri: https://connect.test2.surfconext.nl/oidc/certs
  #            authorization-uri: http://localhost:8080/oidc/authorize
  #            token-uri: http://localhost:8080/oidc/token
  #            jwk-set-uri: http://localhost:8080/oidc/certs

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
    info:
      enabled: true
