logging:
  level:
    root: INFO
    generiek: DEBUG

server:
  port: 8092
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        secure: true

spring:
  jpa:
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./database/student-mobility
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/mobility
#    username: mobility_rw
#    password: secret
  flyway:
    locations: classpath:db/{vendor}/migration

features:
  # Do we allow to mock the different scenario's - only allow on test
  allow_playground: True

# URL of the broker-gui to redirect back after authentication and the credentials of the broker-server to check against
broker:
  url: "http://localhost:3003"
  user: user
  password: secret
  service_registry_base_url: "http://localhost:8091"

# Credentials of the SIS (e.g. Osiris) to check against when reporting back results
sis:
  user: sis
  password: secret

# Details on which custom inteken implementation to call including credentials
backend:
  url: "http://localhost:8093/intake"
  api_user: user
  api_password: secret

oidc:
  acr-context-class-ref: https://eduid.nl/trust/affiliation-student
  client-id: student.mobility.rp.localhost
  client-secret: secret
  redirect-uri: http://localhost:8092/redirect_uri
  authorization-uri: https://connect.test2.surfconext.nl/oidc/authorize
  token-uri: https://connect.test2.surfconext.nl/oidc/token
  jwk-set-uri: https://connect.test2.surfconext.nl/oidc/certs
  #            authorization-uri: http://localhost:8080/oidc/authorize
  #            token-uri: http://localhost:8080/oidc/token
  #            jwk-set-uri: http://localhost:8080/oidc/certs

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - health
          - info
      base-path: "/internal"
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
    info:
      enabled: true
  info:
    git:
      mode: full
    defaults:
      enabled: true
